/// Real Groth16 proof generation via a hidden WebView running snarkjs.
///
/// Flutter/Dart has no native JS/WASM execution environment, and snarkjs
/// (the library that actually implements groth16.fullProve()) is plain
/// JS + WASM. Rather than reimplement Groth16 proving from scratch in Dart
/// — a much larger and more error-prone undertaking than the Poseidon port
/// — this bridges to a hidden WebView running the SAME snarkjs bundle and
/// the SAME auth.wasm/auth.zkey circuit files the web app and backend
/// already use and trust. The proof this produces is genuinely real: it is
/// generated by the real snarkjs prover, not synthesized or faked.
///
/// IMPORTANT — why this loads everything as inlined/embedded data rather
/// than via file paths or asset URLs:
/// Android WebView's file:// scheme (what loadFlutterAsset/loadHtmlString
/// render under) blocks arbitrary absolute-path file access
/// (net::ERR_ACCESS_DENIED) and resolves relative paths against the
/// loaded document's own directory rather than the Flutter asset root —
/// neither approach reliably reaches bundled Flutter assets from inside
/// the WebView's JS context. The actual fix, verified against snarkjs's
/// real source (node_modules/snarkjs/src/wtns_calculate.js and
/// node_modules/fastfile/src/fastfile.js): fastfile.readExisting()
/// explicitly special-cases a Uint8Array input as in-memory data,
/// bypassing file/URL access entirely — and the zkey loading path
/// (via @iden3/binfileutils) goes through that exact same mechanism.
/// So: snarkjs.min.js is read as a string and inlined directly into the
/// HTML document; auth.wasm/auth.zkey are read as bytes, base64-encoded,
/// and passed into the JS call, where they're decoded back to
/// Uint8Array and handed straight to snarkjs — no file access of any
/// kind happens inside the WebView.
///
/// Usage:
///   final prover = GrothProver();
///   await prover.init();                 // load the page, wait for ready
///   final result = await prover.generateProof(
///     secretField: secretFieldDecimal,
///     nonceField:  nonceFieldDecimal,
///   );
///   prover.dispose();
library groth_prover;

import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:webview_flutter/webview_flutter.dart';

class ProverResult {
  final Map<String, dynamic> proof;
  final List<String> publicSignals;
  const ProverResult({required this.proof, required this.publicSignals});
}

class ProverException implements Exception {
  final String message;
  const ProverException(this.message);
  @override
  String toString() => 'ProverException: $message';
}

class GrothProver {
  late final WebViewController _controller;
  Completer<void>? _readyCompleter;
  Completer<ProverResult>? _proofCompleter;
  bool _initialised = false;

  // Circuit assets — read once per instance, reused across generateProof
  // calls if the same GrothProver is kept alive (it currently isn't —
  // AuthBloc creates+disposes one per login attempt — but caching here
  // costs nothing and helps if that changes later).
  String? _wasmBase64;
  String? _zkeyBase64;

  /// Loads the hidden prover page and waits for snarkjs to report ready.
  /// Must be called once before generateProof(). Throws ProverException
  /// if the page fails to load or snarkjs fails to initialise within the
  /// timeout.
  Future<void> init() async {
    if (_initialised) return;

    _readyCompleter = Completer<void>();
    final List<String> resourceErrors = [];

    // Read snarkjs and the prover page template as text, and inline
    // snarkjs directly into the HTML — see file header for why.
    final String snarkjsSource =
        await rootBundle.loadString('assets/vendor/snarkjs.min.js');
    final String pageTemplate =
        await rootBundle.loadString('assets/prover/prover.html');

    if (!pageTemplate.contains('<head>')) {
      throw const ProverException(
        'Failed to inline snarkjs into prover.html — no <head> tag found '
        'to inject the script after. Check assets/prover/prover.html.',
      );
    }

    final String html = pageTemplate.replaceFirst(
      '<head>',
      '<head>\n<script>\n$snarkjsSource\n</script>',
    );

    // Read the circuit files as bytes and base64-encode for passing
    // through the JS bridge (see class doc for why bytes, not paths).
    final ByteData wasmData = await rootBundle.load('assets/circuits/auth.wasm');
    final ByteData zkeyData = await rootBundle.load('assets/circuits/auth.zkey');
    _wasmBase64 = base64Encode(wasmData.buffer.asUint8List(
      wasmData.offsetInBytes, wasmData.lengthInBytes,
    ));
    _zkeyBase64 = base64Encode(zkeyData.buffer.asUint8List(
      zkeyData.offsetInBytes, zkeyData.lengthInBytes,
    ));

    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onWebResourceError: (error) {
            resourceErrors.add(
              '[${error.errorCode}] ${error.description} (${error.url ?? "unknown url"})',
            );
          },
        ),
      )
      ..addJavaScriptChannel(
        'ProverChannel',
        onMessageReceived: _onChannelMessage,
      );

    await _controller.loadHtmlString(html);

    try {
      await _readyCompleter!.future.timeout(const Duration(seconds: 20));
    } on TimeoutException {
      final detail = resourceErrors.isNotEmpty
          ? '\n\nResource load errors:\n${resourceErrors.join('\n')}'
          : '';
      throw ProverException(
        'Prover page did not become ready within 20s — snarkjs may have '
        'failed to load or execute.$detail',
      );
    } catch (e) {
      final detail = resourceErrors.isNotEmpty
          ? '\n\nResource load errors:\n${resourceErrors.join('\n')}'
          : '';
      throw ProverException('${e is ProverException ? e.message : e}$detail');
    }

    _initialised = true;
  }

  /// Generates a REAL Groth16 proof for the auth circuit.
  ///
  /// [secretField] and [nonceField] must already be BN254-field-reduced
  /// decimal strings (i.e. the output of poseidon_bn254.dart's
  /// hexToField(...).toString()) — the same reduction witness.ts performs
  /// on the web side, so mobile and web produce identical witnesses for
  /// identical secret/nonce inputs.
  Future<ProverResult> generateProof({
    required String secretField,
    required String nonceField,
  }) async {
    if (!_initialised) {
      throw const ProverException('GrothProver.init() must be called before generateProof()');
    }

    _proofCompleter = Completer<ProverResult>();

    final inputJson = jsonEncode({
      'secretField': secretField,
      'nonceField':  nonceField,
      'wasmBase64':  _wasmBase64,
      'zkeyBase64':  _zkeyBase64,
    });

    // runJavaScript (not runJavaScriptReturningResult) since the actual
    // result arrives asynchronously via ProverChannel.postMessage — proof
    // generation can take a few seconds and we don't want to block here on
    // a synchronous JS return value.
    await _controller.runJavaScript('generateProof(${jsonEncode(inputJson)})');

    try {
      return await _proofCompleter!.future.timeout(const Duration(seconds: 60));
    } on TimeoutException {
      throw const ProverException(
        'Proof generation timed out after 60s. This usually means '
        'fullProve() is taking unusually long on this device, or failed '
        'silently without posting an error back.',
      );
    }
  }

  void _onChannelMessage(JavaScriptMessage message) {
    Map<String, dynamic> payload;
    try {
      payload = jsonDecode(message.message) as Map<String, dynamic>;
    } catch (e) {
      _proofCompleter?.completeError(
        ProverException('Malformed message from prover page: ${message.message}'),
      );
      return;
    }

    // Ready signal (sent once, on page load)
    if (payload.containsKey('ready')) {
      if (payload['ready'] == true && !(_readyCompleter?.isCompleted ?? true)) {
        _readyCompleter!.complete();
      } else if (payload['ready'] == false && !(_readyCompleter?.isCompleted ?? true)) {
        _readyCompleter!.completeError(
          ProverException(payload['error']?.toString() ?? 'snarkjs failed to initialise'),
        );
      }
      return;
    }

    // Proof result
    if (_proofCompleter == null || _proofCompleter!.isCompleted) return;

    final ok = payload['ok'] == true;
    if (!ok) {
      _proofCompleter!.completeError(
        ProverException(payload['error']?.toString() ?? 'Unknown prover error'),
      );
      return;
    }

    try {
      final proof = payload['proof'] as Map<String, dynamic>;
      final rawSignals = payload['publicSignals'] as List<dynamic>;
      final publicSignals = rawSignals.map((e) => e.toString()).toList();
      _proofCompleter!.complete(ProverResult(proof: proof, publicSignals: publicSignals));
    } catch (e) {
      _proofCompleter!.completeError(
        ProverException('Malformed proof result from prover page: $e'),
      );
    }
  }

  /// Release the underlying WebView. Call when done with this prover
  /// instance (e.g. after a successful or failed login attempt) — don't
  /// keep it alive across the whole app lifetime unnecessarily.
  void dispose() {
    _initialised = false;
    _wasmBase64 = null;
    _zkeyBase64 = null;
  }
}
